# 🛒 E-Commerce Sales Data cleaning (Part 1)

---

## 📌 About the Dataset

This dataset contains transactional data from an e-commerce platform.  
Each row represents a single order placed by a customer.

The dataset includes:
- Customer details  
- Product categories  
- Sales and profit values  
- Payment methods  
- Ratings and order dates  

---

## 🎯 Objective of This Notebook

Before performing any analysis, it is essential to clean and prepare the dataset.

In this notebook, we will:
1. Understand the structure of the dataset  
2. Identify missing and inconsistent data  
3. Clean and standardize the dataset  

This ensures that the data becomes reliable for further processing.

## 📚 Step 1: Importing Required Libraries

We use **pandas** for handling structured data and **numpy** for numerical operations.

In [ ]:
import pandas as pd
import numpy as np

## 📥 Step 2: Loading the Dataset

The dataset is loaded into a pandas DataFrame.

Let us first view the initial rows to understand how the data looks.

In [ ]:

df = pd.read_excel('Sales_ecommerce_data set (1).xlsx')

In [28]:
df.head()

,Order_ID,Customer_Name,Region,City,Product_Category,Sales_Amount,Profit,Discount_Percent,Quantity,Payment_Method,Order_Date,Customer_Rating
0,ORD10000,Rachel Booth,North,Hyderabad,Unknown,6241.79,1297.37,5.0,4,UPI,16-10-2024,1.0
1,ORD10001,Chase Johnston,South,Hyderabad,Unknown,4654.34,-335.28,20.0,1,Cash,31-01-2023,3.0
2,ORD10002,Johnathan Castillo,south,Bangalore,Home,6619.22,1438.65,5.0,7,Net Banking,08-04-2025,3.0
3,ORD10003,Pamela Garcia,West,Kochi,Sports,8807.57,-1551.03,15.0,9,upi,10-09-2024,3.0
4,ORD10004,Sara Simmons,North,Bangalore,Electronics,4414.62,-714.04,10.0,4,Net Banking,14-08-2024,3.0

### 🔍 Observation

- Each row represents an order
- Columns include customer, product, and transaction details
- Data appears structured but may contain inconsistencies

## 📊 Step 3: Understanding Dataset Structure

Before cleaning, we must understand:
- Number of rows and columns  
- Data types  
- Column names

In [29]:
df.shape

(3050, 12)

In [30]:
df.columns

Index(['Order_ID', 'Customer_Name', 'Region', 'City', 'Product_Category',
       'Sales_Amount', 'Profit', 'Discount_Percent', 'Quantity',
       'Payment_Method', 'Order_Date', 'Customer_Rating'],
      dtype='object')

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3050 entries, 0 to 3049
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          3050 non-null   object
 1   Customer_Name     3050 non-null   object
 2   Region            3050 non-null   object
 3   City              3050 non-null   object
 4   Product_Category  3050 non-null   object
 5   Sales_Amount      3050 non-null   float64
 6   Profit            3050 non-null   float64
 7   Discount_Percent  3050 non-null   float64
 8   Quantity          3050 non-null   int64
 9   Payment_Method    3050 non-null   object
 10  Order_Date        3050 non-null   object
 11  Customer_Rating   3050 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 286.1+ KB

### 🔍 Observations

- The dataset contains multiple features related to sales and customers  
- Some columns have missing values  
- `Order_Date` is stored as an object instead of datetime  

This indicates the need for preprocessing.

## ❗ Step 4: Identifying Missing Values

Missing values can lead to incorrect analysis, so they must be handled carefully.

In [32]:
df.isnull().sum()

Order_ID            0
Customer_Name       0
Region              0
City                0
Product_Category    0
Sales_Amount        0
Profit              0
Discount_Percent    0
Quantity            0
Payment_Method      0
Order_Date          0
Customer_Rating     0
dtype: int64

### 🔍 Observations

Missing values are present in:
- Customer_Name  
- Product_Category  
- Sales_Amount  
- Discount_Percent  
- Customer_Rating  

These need to be handled using appropriate techniques.

## 🛠️ Step 5: Handling Missing Values

We apply different strategies based on the type of data:

### 🔹 Categorical Data
Missing values are replaced with **"Unknown"**

### 🔹 Numerical Data
- Sales_Amount → filled with mean  
- Discount_Percent → filled with median  
- Customer_Rating → filled with median  

This approach maintains data balance without introducing bias.

In [27]:
import pandas as pd

df = pd.read_excel('Sales_ecommerce_data set (1).xlsx')

df['Customer_Name'] = df['Customer_Name'].fillna('Unknown')
df['Product_Category'] = df['Product_Category'].fillna('Unknown')
df['Payment_Method'] = df['Payment_Method'].fillna('Unknown')

df['Sales_Amount'] = df['Sales_Amount'].fillna(df['Sales_Amount'].mean())
df['Discount_Percent'] = df['Discount_Percent'].fillna(df['Discount_Percent'].median())
df['Customer_Rating'] = df['Customer_Rating'].fillna(df['Customer_Rating'].median())

In [33]:
df.isnull().sum()

Order_ID            0
Customer_Name       0
Region              0
City                0
Product_Category    0
Sales_Amount        0
Profit              0
Discount_Percent    0
Quantity            0
Payment_Method      0
Order_Date          0
Customer_Rating     0
dtype: int64

### ✅ Result

All missing values have been handled successfully.  
The dataset is now complete and consistent.

## 👀 Step 6: Viewing Cleaned Data

Let us view the dataset after handling missing values.

In [34]:
df.head()

,Order_ID,Customer_Name,Region,City,Product_Category,Sales_Amount,Profit,Discount_Percent,Quantity,Payment_Method,Order_Date,Customer_Rating
0,ORD10000,Rachel Booth,North,Hyderabad,Unknown,6241.79,1297.37,5.0,4,UPI,16-10-2024,1.0
1,ORD10001,Chase Johnston,South,Hyderabad,Unknown,4654.34,-335.28,20.0,1,Cash,31-01-2023,3.0
2,ORD10002,Johnathan Castillo,south,Bangalore,Home,6619.22,1438.65,5.0,7,Net Banking,08-04-2025,3.0
3,ORD10003,Pamela Garcia,West,Kochi,Sports,8807.57,-1551.03,15.0,9,upi,10-09-2024,3.0
4,ORD10004,Sara Simmons,North,Bangalore,Electronics,4414.62,-714.04,10.0,4,Net Banking,14-08-2024,3.0

### 🔍 Observation

- Missing values are no longer present  
- Dataset appears cleaner and more structured

## 🔤 Step 7: Standardizing Text Data

Text data often contains inconsistencies like:
- Different letter cases (e.g., "upi", "UPI")  
- Irregular formatting  

We standardize them for consistency.

In [35]:
df['Region'] = df['Region'].str.title()
df['Payment_Method'] = df['Payment_Method'].str.title()

In [36]:
df[['Region', 'Payment_Method']].head()

  Region Payment_Method
0  North            Upi
1  South           Cash
2  South    Net Banking
3   West            Upi
4  North    Net Banking

### ✅ Result

- Text values are now consistent  
- Improves grouping and analysis accuracy

## 🔁 Step 8: Checking for Duplicate Records

Duplicate rows can distort analysis results.

In [37]:
df.duplicated().sum()

np.int64(48)

### 🔍 Observation

If duplicates exist, they must be removed.

## 🧹 Step 9: Removing Duplicate Records

In [38]:
df.drop_duplicates(inplace=True)

In [39]:
df.duplicated().sum()

np.int64(0)

### ✅ Result

Duplicate records have been removed successfully.

## 👁️ Step 10: Final Dataset Preview

In [40]:
df.head()

,Order_ID,Customer_Name,Region,City,Product_Category,Sales_Amount,Profit,Discount_Percent,Quantity,Payment_Method,Order_Date,Customer_Rating
0,ORD10000,Rachel Booth,North,Hyderabad,Unknown,6241.79,1297.37,5.0,4,Upi,16-10-2024,1.0
1,ORD10001,Chase Johnston,South,Hyderabad,Unknown,4654.34,-335.28,20.0,1,Cash,31-01-2023,3.0
2,ORD10002,Johnathan Castillo,South,Bangalore,Home,6619.22,1438.65,5.0,7,Net Banking,08-04-2025,3.0
3,ORD10003,Pamela Garcia,West,Kochi,Sports,8807.57,-1551.03,15.0,9,Upi,10-09-2024,3.0
4,ORD10004,Sara Simmons,North,Bangalore,Electronics,4414.62,-714.04,10.0,4,Net Banking,14-08-2024,3.0

### 🔍 Final Observations

- Dataset is clean  
- Missing values handled  
- Duplicates removed  
- Ready for next preprocessing phase

## 💾 Step 11: Saving Cleaned Dataset

We save the cleaned dataset for further processing in the next notebook.

In [41]:
df.to_csv("cleaned_data_step1.csv", index=False)

## 🏁 Conclusion

In this notebook, we successfully:

- Explored the dataset  
- Identified missing values  
- Handled inconsistencies  
- Removed duplicate records  

The dataset is now clean and ready for transformation and feature engineering.